### creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "JOHN DOE kafka_test",
  "email": "kafka_test123@example.com",
  "address": "ram mandir road",
  "dateOfBirth": "2001-03-02",
  "registeredDate": "2021-11-30"
}
###